# All docs at https://hub.docker.com/_/postgres
services:

  db:
    image: postgres

    #Always restart the container unless it is explicitly stopped or Docker itself is stopped or restarted.
    restart: always

    # set shared memory limit when using docker compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    environment:
      POSTGRES_PASSWORD: example_pass
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user


  # Simple web-based database management tool written in PHP.
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080